name: $(majorVersion).$(minorVersion)$(Rev:.r)
variables:
- name: majorVersion
  value: 9
- name: minorVersion
  value: 0
- name: BuildConfiguration
  value: Release
resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration $(BuildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: custom
    custom: 'pack '
    arguments: '--configuration $(BuildConfiguration) --output $(build.artifactstagingdirectory) --include-symbols --include-source src/NgrokAspNetCore.Lib/NgrokAspNetCore.Lib.csproj'
    buildProperties: 'version=$(Build.BuildNumber)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'