name: $(majorVersion).$(minorVersion)$(Rev:.r)
resources:
- repo: self
queue:
  name: Hosted VS2017
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack'
  inputs:
    command: pack
    buildProperties: 'version=$(Build.BuildNumber)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'