name: Build and Test

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build src/Ngrok.AspNetCore
      run: dotnet build --configuration Release src/Ngrok.AspNetCore
    - name: Test src/Ngrok.AspNetCore
      run: dotnet test --configuration Release test/Ngrok.AspNetCore.UnitTests
